### ISSUE TITLE
We really need this new UI...

### ISSUE THREAD

**Issue by aetinx** [micahlt/informant#20]
![image](https://user-images.githubusercontent.com/65425469/100094850-a31b2700-2e27-11eb-936b-e63c0767c0af.png)

**Comment by micahlt** [comment]
Disagree - what's wrong with the current UI?  It's much more flexible.

**Comment by aetinx** [comment]
Here's another idea:

![image](https://user-images.githubusercontent.com/65425469/100145065-c2d14000-2e65-11eb-8137-20848545a590.png)

**Comment by aetinx** [comment]
> Disagree - what's wrong with the current UI? It's much more flexible.

It just looks really weird when I try to use Inter as the font.

**Comment by micahlt** [comment]
Maybe that's because Inter may not be the right font for a news site 😳

**Comment by aetinx** [comment]
> Maybe that's because Inter may not be the right font for a news site 😳

Bruh moment.

**Comment by aetinx** [comment]
> > Maybe that's because Inter may not be the right font for a news site 😳
> 
> Bruh moment.

About bruh moments...

![image](https://user-images.githubusercontent.com/65425469/100237573-1cd11480-2efd-11eb-92de-ac81192957f9.png)

**Comment by sargent-coding** [comment]
![image](https://user-images.githubusercontent.com/65425469/100247186-0e3c2a80-2f08-11eb-8c97-766a573a9957.png)

**Comment by aetinx** [comment]
I have two new ideas... I really like them.


![Synieq OS and Ryfelta (15)](https://user-images.githubusercontent.com/65425469/100249310-696f1c80-2f0a-11eb-84c1-1744e7a3e278.png)
![Synieq OS and Ryfelta (17)](https://user-images.githubusercontent.com/65425469/100249308-68d68600-2f0a-11eb-9259-aa57fdfee8bf.png)

**Comment by micahlt** [comment]
@sargent-coding I'm not currently actively developing this project, so if you want to take the time to build the CSS for this then by all means please do.
