### ISSUE TITLE
New contact.html and write.html files

### ISSUE THREAD

**Issue by aetinx** [micahlt/informant#22]
![Synieq OS and Ryfelta (11)](https://user-images.githubusercontent.com/65425469/100128115-de305100-2e4d-11eb-8ffc-90c28cbb84f2.png)
![Synieq OS and Ryfelta (12)](https://user-images.githubusercontent.com/65425469/100128113-dd97ba80-2e4d-11eb-93d3-49bc47e4f1ab.png)

**Comment by micahlt** [comment]
@sargent-coding Please explain what this issue is about.
