### ISSUE TITLE
informant.micahlindley.com --> informant.saco.ml

### ISSUE THREAD

**Issue by aetinx** [micahlt/informant#24]
I was wondering if once I an actually talk to Ekmand about managing my saco.ml subdomains (he does all that stuff), if we could use informant.saco.ml instead of the current one. Ekmand just never responds to my DMs or anything. He said he was taking a break from Sargent Coding, which weakens my ways of communication even more.

TL;DR
I want to move domains, but Ekmand manages my subdomains and I can't contact him about it, so I don't think I can actually move domains. 🤷

**Comment by micahlt** [comment]
Why does @-Ekmand- manage your domain?

**Comment by aetinx** [comment]
> Why does @-Ekmand- manage your domain?

Because I asked him about domain stuff whiles ago. But, he never told me how he does whatever happens. Bruh moment.

**Comment by micahlt** [comment]
@sargent-coding I'll speak to Ekmand about relocating this.  Meanwhile, are you still interested in maintaining this project?

**Comment by aetinx** [comment]
> @sargent-coding I'll speak to Ekmand about relocating this. Meanwhile, are you still interested in maintaining this project?

No.

**Comment by micahlt** [comment]
Activity?

**Comment by aetinx** [comment]
> Activity?

More like death.

**Comment by micahlt** [comment]
@aetinx Whoa, hold up - don't delete all the code.  I'm rolling back those commits.

**Comment by aetinx** [comment]
> @aetinx Whoa, hold up - don't delete all the code. I'm rolling back those commits.

Oh, ok then..

**Comment by micahlt** [comment]
GitHub has archive functionality that's for stuff like this.

**Comment by aetinx** [comment]
Ok, but I don't know why you'd need the code for a project that's been dead for a whole year.

**Comment by micahlt** [comment]
It's called archiving.  Like what if I ever decide to resurrect the Informant?  I'd like to have the code accessible.

**Comment by aetinx** [comment]
Alright.
