### ISSUE TITLE
Some images don't appear properly.

### ISSUE THREAD

**Issue by aetinx** [micahlt/informant#4]

**Comment by micahlt** [comment]
Please explain.

**Comment by aetinx** [comment]
Images appear as broken. This is probably because the origin of the images is blocked on the client's/clients' computer. This can be fixed by adding them to the assets folder.

**Comment by micahlt** [comment]
Hm... maybe I can get a Vercel serverless function running to fix that.

**Comment by aetinx** [comment]
Hey @micahlt, we can make another folder in the `assets` folder, maybe called `stories` and then put the pictures in there.
Edit: I'll do this right now. It's better to do something, then do nothing.

**Comment by aetinx** [comment]
Fixed!
